/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LibraryPackage;

//import static LibraryPackage.CreateUser.list;
import java.awt.event.KeyEvent;

/**
 *
 * @author Ayub
 */
import java.io.*;
import java.text.*;
import java.util.*;
import javax.swing.*;
public class CreateBooks extends javax.swing.JFrame {

    /**
     * Creates new form Books
     */
   
    private static Book headNode;
    private static Book tailNode;
   
    private static Librarian loggedIn;
    
    public CreateBooks(){} //no args constructor
    public CreateBooks(Book headNode, Book tailNode, Librarian temp) {
        initComponents();
        this.headNode = headNode;
        this.tailNode = tailNode;
        loggedIn = temp;
    }
    
        /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        isbnField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        genreCMB = new javax.swing.JComboBox<>();
        cancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        afnField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        alnField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        chooseYear = new com.toedter.calendar.JYearChooser();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        isbnField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isbnFieldKeyTyped(evt);
            }
        });
        getContentPane().add(isbnField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 203, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ISBN Number:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Year Published:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Genre:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, -1, -1));

        add.setText("Add Book");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 100, -1));

        genreCMB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "N/a", "Mystery", "Fiction", "Non-Fiction", "Horror", "Technology", "Young Adult", "Romance" }));
        getContentPane().add(genreCMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 203, -1));

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 100, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Legacy Library Catalog");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));
        getContentPane().add(titleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 203, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Book Title:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        afnField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                afnFieldKeyTyped(evt);
            }
        });
        getContentPane().add(afnField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 203, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Author's First Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        alnField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                alnFieldKeyTyped(evt);
            }
        });
        getContentPane().add(alnField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 203, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Author's Last Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));
        getContentPane().add(chooseYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 200, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LibraryPackage/Bookshelves-Background2.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 480));

        setSize(new java.awt.Dimension(816, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //Activity: returns the screen back to the login screen
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
        LibrarianHomepage bkl = new LibrarianHomepage(loggedIn);
        bkl.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    //Activity: restricts the user input in the author text area to only alphabets (no numbers)
    private void afnFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_afnFieldKeyTyped
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACK_SPACE)||  c==KeyEvent.VK_DELETE ))
            evt.consume();
    }//GEN-LAST:event_afnFieldKeyTyped
    
    //Activity: restricts the user input in the author text area to only alphabets (no numbers)
    private void alnFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_alnFieldKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) ||  (c==KeyEvent.VK_BACK_SPACE)||  c==KeyEvent.VK_DELETE ))
            evt.consume();
    }//GEN-LAST:event_alnFieldKeyTyped

    //Activity: restricts the user input in the ISBN text area to only numbers (no alphabets)
    private void isbnFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isbnFieldKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || c == KeyEvent.VK_BACK_SPACE) || c == KeyEvent.VK_DELETE){
            evt.consume();
        }
    }//GEN-LAST:event_isbnFieldKeyTyped

    /*
    Precondition: the book list is filled with the books read from file
    Postcondition: a new book is added to the list of books and the file is updated with the new book
    Activity: creates a new book with the given title, author, isbn, genre, and published date input by the librarian
              also updates the file to include the new book added, when the librarian returns to the database screen
              the file will be read in to the list of books with the new one included
    */
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        boolean createBook = true;
        String title = titleField.getText();//gets the tile of the Book
        String fi = afnField.getText();    
        String li = alnField.getText();     
                
        String wordnum = isbnField.getText(); //the string needs to be parsed for an int
        int num = 0;
            if(!(wordnum.equals(""))){//error check if it's empty it wont parse int
                num = Integer.parseInt(wordnum); //turns the string into a number
            }
            

        String date = ""+chooseYear.getYear();
        int pub = 0;
        if(!(date.equals(""))){
            pub = Integer.parseInt(date);
        }
        System.out.print(pub);
        String genre = (String)genreCMB.getSelectedItem();
        if(title.equals("") || fi.equals("") || li.equals("") || num == 0 || genre.equals("N/a") || date.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill in all required fields.");
            createBook = false;
        }
        
        int YesOrNo = 0;
        boolean copyExist = false;
        Book currentNode = headNode;
        if(headNode != null){
            do{
                if(currentNode.title.equals(title)){
                    copyExist = true;
                }
                currentNode = currentNode.nextNode;
            }while(currentNode != null);
        }
        if(copyExist == true){
            YesOrNo = JOptionPane.showConfirmDialog(null, "Do you want to add another copy of this book.","",JOptionPane.YES_NO_OPTION);
        }
        
        if(YesOrNo == 0){
            if(createBook == true){
                Book newNode = new Book (title, fi, li, num, pub, genre, null);
                JOptionPane.showMessageDialog(null, "A new book was added to the library.");
                
                if(headNode == null){
                    headNode = newNode;
                }else{
                    tailNode.nextNode = newNode;
                }
                tailNode = newNode;
                
                //after adding the Book to the arraylist, the program writes to the file to update it
                try{
                    FileOutputStream fos= new FileOutputStream("Book Info");
                    ObjectOutputStream oos= new ObjectOutputStream(fos);
                    oos.writeObject(headNode); //this is a way to store the arraylist in a file
                    oos.close();
                    fos.close();
                }catch(IOException ioe){
                    ioe.printStackTrace();
                }
                this.dispose();//after updating, goes back to the admin homepage
                LibrarianHomepage bkl = new LibrarianHomepage(loggedIn);
                bkl.setVisible(true);
            }
        }
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField afnField;
    private javax.swing.JTextField alnField;
    private javax.swing.JButton cancel;
    private com.toedter.calendar.JYearChooser chooseYear;
    private javax.swing.JComboBox<String> genreCMB;
    private javax.swing.JTextField isbnField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField titleField;
    // End of variables declaration//GEN-END:variables
}
